services:
  albion-square-spring-app:
    build:
      dockerfile: ./spring-app.Dockerfile
  albion-square-svelte-app:
    build:
      dockerfile: ./svelte-app.Dockerfile
    ports:
      - "3000:3000"
