name: Dev PR CI

on:
  pull_request:
    branches:
      - dev

jobs:
  spring-app-build:
    name: Spring App Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file spring-app.Dockerfile --tag ghcr.io/snow-fox-studio-llc/albion-square-spring-app:pr-latest
  svelte-app-build:
    name: Svelte App Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file svelte-app.Dockerfile --tag ghcr.io/snow-fox-studio-llc/albion-square-svelte-app:pr-latest
