name: Dev PR CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/snow-fox-studio-llc/albion-square:latest
