name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  spring-app-build:
    name: Spring App Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file spring-app.Dockerfile --tag ghcr.io/snow-fox-studio-llc/albion-square-spring-app:latest
      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Push Docker image
        run: docker push ghcr.io/snow-fox-studio-llc/albion-square-spring-app:latest
  svelte-app-build:
    name: Svelte App Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . --file svelte-app.Dockerfile --tag ghcr.io/snow-fox-studio-llc/albion-square-svelte-app:latest
      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Push Docker image
        run: docker push ghcr.io/snow-fox-studio-llc/albion-square-svelte-app:latest
